### ISSUE TITLE
Hi there, is this still live?

### ISSUE THREAD

**Issue by InfiniFlix** [jafrewa/kisscartoon#21]
I installed this but cannot seem to get it to scrape Kiss Cartoon

**Comment by jvonhoff** [comment]
See issue #18 .  Until that is fixed, nothing will scrape.

**Comment by InfiniFlix** [comment]
Many thanks for the update.

**Comment by jvonhoff** [comment]
You bet.  I'm closing this as a duplicate of #18

**Comment by InfiniFlix** [comment]
thx!
